const CDatafilter = [
        {
    id: 1,
    name: "INDIA",
    description:"India Covid statistics",
    description1:"No. of cases 45,024,190",
    description2:"No. of deaths 533,439",
    description3:"No. of recovery 44,490,751",
    image1:"./images/INDV.png",
    image2:"./images/INDP.png",
    image3:"./images/INDC.png",
    image4:"./images/INDR.png",
        },
        {
            id: 2,
            name: "USA",
            description:"USA Covid statistics",
            description1:"No. of cases 110,672,611",
            description2:"No. of deaths 1,193,166",
            description3:"No. of recovery 108,402,627",
            image1:"./images/USAV.png",
            image2:"./images/USAP.png",
            image3:"./images/USAC.png",
            image4:"./images/USAR.png",
    
                },
        {
            id: 3,
            name: "CHINA",
            description:"China Covid statistics",
            description1:"No. of cases 503,302",
            description2:"No. of deaths 5,272",
            description3:"No. of recovery 379,053",
            image1:"./images/CHNV.png",
            image2:"./images/CHNP.png",
            image3:"./images/CHNC.png",
            image4:"./images/CHNR.png",
                },
                    {
                        id: 4,
                        name: "CANADA",
                        description:"Canada Covid statistics",
                        description1:"No. of cases 4,910,081",
                        description2:"No. of deaths 57,711",
                        description3:"No. of recovery 3,927,670",
                        image1:"./images/CANV.png",
                        image2:"./images/CANP.png",
                        image3:"./images/CANC.png",
                        image4:"./images/CANR.png",
                            },
                {
                    id: 5,
                    name: "MEXICO",
                    description:"Mexico Covid statistics",
                    description1:"No. of cases 7,702,809",
                    description2:"No. of deaths 334,958",
                    description3:"No. of recovery 6,899,865",
                    image1:"./images/MEXV.png",
                    image2:"./images/MEXP.png",
                    image3:"./images/MEXC.png",
                    image4:"./images/MEXR.png",
                        },
                {
                    id: 6,
                    name: "BRAZIL",
                    description:"Brazil Covid statistics",
                    description1:"No. of cases 38,303,320",
                    description2:"No. of deaths 709,195",
                    description3:"No. of recovery 36,249,161",
                    image1:"./images/BRAV.png",
                    image2:"./images/BRAP.png",
                    image3:"./images/BRAC.png",
                    image4:"./images/BRAR.png",
                        },
                {
                    id: 7,
                    name: "RUSSIA",
                    description:"Russia Covid statistics",
                    description1:"No. of cases 23,851,450",
                    description2:"No. of deaths 401,834",
                    description3:"No. of recovery 23,268,040",
                    image1:"./images/RUSV.png",
                    image2:"./images/RUSP.png",
                    image3:"./images/RUSC.png",
                    image4:"./images/RUSR.png",
                        },
                {
                    id: 8,
                    name: "PAKISTAN",
                    description:"Pakistan Covid statistics",
                    description1:"No. of cases 1,581,936",
                    description2:"No. of deaths 30,664",
                    description3:"No. of recovery 1,538,689",
                    image1:"./images/PAKV.png",
                    image2:"./images/PAKP.png",
                    image3:"./images/PAKC.png",
                    image4:"./images/PAKR.png",
                        },
                {
                    id: 9,
                    name: "INDONESIA",
                    description:"Indonesia Covid statistics",
                    description1:"No. of cases 6,826,664",
                    description2:"No. of deaths 161,954",
                    description3:"No. of recovery 6,647,104",
                    image1:"./images/INSV.png",
                    image2:"./images/INSP.png",
                    image3:"./images/INSC.png",
                    image4:"./images/INSR.png",
                        },
                {
                    id: 10,
                    name: "NIGERIA",
                    description:"Nigeria Covid statistics",
                    description1:"No. of cases 267,173",
                    description2:"No. of deaths 3,155",
                    description3:"No. of recovery 259,953",
                    image1:"./images/NIGV.png",
                    image2:"./images/NIGP.png",
                    image3:"./images/NIGC.png",
                    image4:"./images/NIGR.png",
                        },
                        {
                            id: 11,
                            name: "WORLD",
                            description:"World Covid statistics",
                            description1:"No. of cases 702,412,742",
                            description2:"No. of deaths 6,974,185",
                            description3:"No. of recovery 673,336,245",
                            image1:"./images/WORLDV.png",
                            image2:"./images/WORLDP.png",
                            image3:"./images/WORLDC.png",
                            image4:"./images/WORLDR.png",
                                }
]

export {CDatafilter};